"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { address } from "@solana/kit";
import { useCluster } from "../../components/cluster-context";
import { WalletButton } from "../../components/wallet-button";
import { useWallet } from "../../lib/wallet/context";
import { useSendTransaction } from "../../lib/hooks/use-send-transaction";
import { fetchOrganization, organizationPda } from "../../lib/organizations/chain";
import { createCampaignIx, listCampaigns, type Campaign } from "../../lib/campaigns/chain";
import { parseSolAmount, displaySol } from "../../lib/campaigns/amount";

type Item = { campaign: Campaign; title: string; description: string; disasterType: string; location: string };
function Placeholder() { return <div className="relative aspect-[16/10] overflow-hidden bg-[#d9d1c2]"><div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(255,255,255,.52),transparent_48%,rgba(48,38,28,.16))]" /><span className="absolute left-3 top-3 border border-emerald-700/25 bg-emerald-100/90 px-2 py-1 text-xs font-bold text-emerald-900">✓ Active</span><span className="absolute bottom-3 right-3 bg-white/70 px-2 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-[#625a4e]">Dummy image</span></div>; }

export default function CampaignsPage() {
  const { cluster, getExplorerUrl } = useCluster(); const { wallet } = useWallet(); const { send, isSending } = useSendTransaction(); const walletAddress = wallet?.account.address;
  const [items, setItems] = useState<Item[]>([]); const [orgs, setOrgs] = useState<Awaited<ReturnType<typeof fetchOrganization>>[]>([]); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [disasterType, setDisasterType] = useState(""); const [location, setLocation] = useState(""); const [goal, setGoal] = useState(""); const [org, setOrg] = useState(""); const [error, setError] = useState(""); const [signature, setSignature] = useState(""); const [stage, setStage] = useState("");
  const [search, setSearch] = useState(""); const [typeFilter, setTypeFilter] = useState("All disasters"); const [statusFilter, setStatusFilter] = useState("Active"); const [sort, setSort] = useState("Newest");
  const refresh = useCallback(async () => { if (cluster !== "devnet" && cluster !== "localnet") return; try { const campaigns = await listCampaigns(cluster); const listed = await Promise.all(campaigns.map(async (campaign) => { try { const res = await fetch(`/api/campaigns/metadata?uri=${encodeURIComponent(campaign.metadataUri)}`); const data = await res.json(); if (data.digest === campaign.metadataDigest) return { campaign, title: data.metadata.title as string, description: data.metadata.description as string, disasterType: data.metadata.disasterType as string, location: data.metadata.location as string }; } catch {} return { campaign, title: "Metadata unavailable", description: "Campaign metadata is awaiting verification.", disasterType: "Unknown", location: "Unknown" }; })); setItems(listed); if (walletAddress) { const mine = await fetchOrganization(cluster, await organizationPda(address(walletAddress))); const all = mine ? [mine] : []; const remote = await fetch(`/api/organizations?cluster=${cluster}`).then((r) => r.ok ? r.json() : []).catch(() => []); for (const row of remote) if (row.authority === walletAddress && !all.some((x) => x?.address === row.address)) { const found = await fetchOrganization(cluster, address(row.address)); if (found) all.push(found); } setOrgs(all); if (all.length && !org) setOrg(all[0]!.address); } } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }, [cluster, walletAddress, org]);
  useEffect(() => { const timer = setTimeout(() => void refresh(), 0); return () => clearTimeout(timer); }, [refresh]);
  const create = async () => { setError(""); setSignature(""); try { if (!walletAddress) throw new Error("Connect a wallet"); const selected = orgs.find((x) => x?.address === org); if (!selected || !selected.verified || selected.status !== "Active") throw new Error("Choose an active, verified organization"); setStage("Saving metadata"); const response = await fetch("/api/metadata", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind: "campaign", metadata: { title, description, disasterType, location } }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setStage("Awaiting wallet signature"); const tx = await send({ instructions: [await createCampaignIx(selected.address, address(walletAddress), selected.nextCampaignId, parseSolAmount(goal), null, body.digest, body.uri)] }); setSignature(tx); setStage("Campaign created"); await refresh(); } catch (e) { setStage("Failed"); setError(e instanceof Error ? e.message : String(e)); } };
  const types = useMemo(() => Array.from(new Set(items.map((item) => item.disasterType).filter((type) => type !== "Unknown"))), [items]);
  const visible = useMemo(() => items.filter((item) => `${item.title} ${item.location}`.toLowerCase().includes(search.toLowerCase()) && (typeFilter === "All disasters" || item.disasterType === typeFilter) && (statusFilter === "All statuses" || item.campaign.status === statusFilter)).sort((a, b) => sort === "Most funded" ? Number(b.campaign.amountRaised - a.campaign.amountRaised) : Number(b.campaign.createdAt - a.campaign.createdAt)), [items, search, sort, statusFilter, typeFilter]);
  return <main className="min-h-screen bg-[#f7f4ed] px-5 py-10 text-[#302a21] md:px-8"><div className="mx-auto max-w-[1216px] space-y-8">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-[#d8d0c2] pb-7"><div><p className="mb-3 text-xs font-extrabold tracking-[.12em] text-red-700">— {items.filter((item) => item.campaign.status === "Active").length} ACTIVE ACROSS INDEXED REGIONS</p><h1 className="font-serif text-5xl">Relief campaigns</h1><p className="mt-3 text-[#776f63]">Explore urgent work, inspect every fund trail, and donate with complete visibility.</p></div><WalletButton /></header>
    {cluster !== "devnet" && cluster !== "localnet" && <p className="border border-amber-500 bg-amber-50 p-4">Select Devnet or localnet to use canonical campaigns.</p>}{error && <p role="alert" className="border border-red-500 bg-red-50 p-3">{error}</p>}{stage && <p role="status" className="border border-[#d8d0c2] bg-[#fffdf8] p-3">{stage} {signature && <a className="underline" href={getExplorerUrl(`/tx/${signature}`)} target="_blank" rel="noreferrer">View transaction</a>}</p>}
    <section className="grid gap-3 border border-[#d8d0c2] bg-[#fffdf8] p-3 md:grid-cols-[minmax(0,1fr)_190px_190px_190px]"><label className="relative"><span className="pointer-events-none absolute left-3 top-3 text-[#776f63]">⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search campaign or location" className="w-full border border-[#cfc4b4] bg-white py-3 pl-10 pr-3 text-sm outline-red-700" /></label><select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)} className="border border-[#cfc4b4] bg-white px-3 text-sm"><option>All disasters</option>{types.map((type) => <option key={type}>{type}</option>)}</select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="border border-[#cfc4b4] bg-white px-3 text-sm"><option>Active</option><option>Draft</option><option>PendingReview</option><option>Paused</option><option>Closed</option><option>All statuses</option></select><select value={sort} onChange={(event) => setSort(event.target.value)} className="border border-[#cfc4b4] bg-white px-3 text-sm"><option>Newest</option><option>Most funded</option></select></section>
    {orgs.some((x) => x?.verified && x.status === "Active") && <section className="space-y-3 border border-[#d8d0c2] bg-[#fffdf8] p-5"><h2 className="font-serif text-2xl">Create campaign</h2><p className="text-sm text-[#776f63]">Campaign metadata is saved and hash-verified by AidTrace.</p><select className="w-full border p-2" value={org} onChange={(e) => setOrg(e.target.value)}>{orgs.filter((x) => x?.verified && x.status === "Active").map((x) => <option key={x!.address} value={x!.address}>{x!.address}</option>)}</select><input className="w-full border p-2" placeholder="Campaign title" value={title} onChange={(e) => setTitle(e.target.value)} /><textarea className="w-full border p-2" placeholder="Description" value={description} onChange={(e) => setDescription(e.target.value)} /><input className="w-full border p-2" placeholder="Disaster type" value={disasterType} onChange={(e) => setDisasterType(e.target.value)} /><input className="w-full border p-2" placeholder="Location" value={location} onChange={(e) => setLocation(e.target.value)} /><input className="w-full border p-2" placeholder="Goal in SOL" value={goal} onChange={(e) => setGoal(e.target.value)} /><button className="bg-red-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={isSending || !title || !description || !disasterType || !location || !goal} onClick={() => void create()}>Create draft</button></section>}
    <div className="flex items-center justify-between"><p className="text-sm font-bold">{visible.length} campaign{visible.length === 1 ? "" : "s"}</p><button type="button" onClick={() => { setSearch(""); setTypeFilter("All disasters"); setStatusFilter("Active"); setSort("Newest"); }} className="text-sm font-bold underline">Clear filters</button></div>
    <section className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{visible.map((item) => { const percentage = item.campaign.targetAmount ? Number((item.campaign.amountRaised * 100n) / item.campaign.targetAmount) : 0; return <Link key={item.campaign.address} href={`/campaigns/${item.campaign.address}`} className="group overflow-hidden border border-[#d8d0c2] bg-[#fffdf8] shadow-[0_8px_30px_-26px_#302a21] transition hover:-translate-y-0.5"><Placeholder /><div className="p-5"><h2 className="font-serif text-2xl leading-tight">{item.title}</h2><p className="mt-2 text-sm text-[#776f63]">⌾ {item.location}</p><p className="mt-4 line-clamp-2 text-sm leading-relaxed text-[#625a4e]">{item.description}</p><div className="mt-6 flex items-end justify-between"><div><strong className="font-serif text-xl">{displaySol(item.campaign.amountRaised)} SOL</strong><p className="text-xs text-[#776f63]">of {displaySol(item.campaign.targetAmount)} SOL</p></div><div className="text-right"><strong className="text-xs">{percentage}%</strong><p className="mt-1 text-xs text-emerald-800">◎ {item.campaign.nextDonationId.toString()} donations</p></div></div><div className="mt-3 h-2 bg-[#e8e1d6]"><div className="h-full bg-red-700" style={{ width: `${Math.min(percentage, 100)}%` }} /></div></div></Link>; })}</section>
    {!visible.length && <section className="border border-dashed border-[#bdb3a3] bg-[#fffdf8] p-10 text-center"><h2 className="font-serif text-2xl">No campaigns match these filters.</h2><p className="mt-2 text-sm text-[#776f63]">Try a different search term or clear the current filters.</p></section>}<p className="text-xs text-[#776f63]">Campaign amounts, status, and metadata are real selected-cluster data. Cover images are intentional dummy placeholders.</p>
  </div></main>;
}
