[toolchain]
anchor_version = "1.1.1"
solana_version = "3.1.10"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aidtrace = "FsnkvMW3VLrpY1oarGW3ePS22bwoCNpP9PZdMFGW6E4M"

[programs.localnet]
aidtrace = "FsnkvMW3VLrpY1oarGW3ePS22bwoCNpP9PZdMFGW6E4M"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
