[toolchain]
anchor_version = "1.1.1"
solana_version = "3.1.10"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aidtrace = "8tcYj5qT3GAwhhHmK8UgHtyCZq7MgD8nCYGhC7rwEW5r"

[programs.localnet]
aidtrace = "8tcYj5qT3GAwhhHmK8UgHtyCZq7MgD8nCYGhC7rwEW5r"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
