"use client";
import { useCallback, useEffect, useState } from "react";
import { address } from "@solana/kit";
import { useCluster } from "../../components/cluster-context";
import { WalletButton } from "../../components/wallet-button";
import { useWallet } from "../../lib/wallet/context";
import { useSendTransaction } from "../../lib/hooks/use-send-transaction";
import { fetchAdmin, rpcCall, setStatusIx, setVerifiedIx } from "../../lib/organizations/chain";
import { setCampaignStatusIx } from "../../lib/campaigns/chain";
import { resolveFraudFlagIx } from "../../lib/trust-chain";

type Review = { organizations: any[]; campaigns: any[]; disasters: any[] };
export default function AdminReviewPage() {
  const { cluster, getExplorerUrl } = useCluster(); const { wallet } = useWallet(); const { send, isSending } = useSendTransaction();
  const [allowed, setAllowed] = useState(false); const [data, setData] = useState<Review>({ organizations: [], campaigns: [], disasters: [] }); const [message, setMessage] = useState("");
  const walletAddress = wallet?.account.address;
  const load = useCallback(async () => {
    if (!allowed || !wallet?.signMessage || !walletAddress) throw new Error("A connected admin wallet with message signing is required");
    const challengeResponse = await fetch("/api/admin/challenge", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ wallet: walletAddress, action: "read_review_queue" }) });
    const challenge = await challengeResponse.json();
    if (!challengeResponse.ok) throw new Error(challenge.error || "Could not authorize review queue");
    const signed = await wallet.signMessage(new TextEncoder().encode(challenge.message));
    if (new TextDecoder().decode(signed.message) !== challenge.message) throw new Error("Wallet returned a different signed message");
    const response = await fetch("/api/admin/review", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ wallet: walletAddress, action: "read_review_queue", nonce: challenge.nonce, message: challenge.message, signature: btoa(String.fromCharCode(...signed.signature)), cluster }) });
    const body = await response.json();
    if (!response.ok) throw new Error(body.error || "Review data unavailable");
    setData(body);
  }, [allowed, cluster, wallet, walletAddress]);
  useEffect(() => { let live = true; setData({ organizations: [], campaigns: [], disasters: [] }); setMessage(""); if (!walletAddress) { setAllowed(false); return; } void fetchAdmin(cluster).then(a => { if (live) setAllowed(a === walletAddress); }).catch(() => live && setAllowed(false)); return () => { live = false; }; }, [cluster, walletAddress]);
  useEffect(() => { void load().catch(e => setMessage(e instanceof Error ? e.message : "Review data unavailable")); }, [load]);
  const transact = async (build: () => Promise<any>, label: string) => { try { setMessage("Awaiting wallet approval"); const signature = await send({ instructions: [await build()] }); for (let i = 0; i < 30; i++) { const s = await rpcCall<any>(cluster, "getSignatureStatuses", [[signature], { searchTransactionHistory: true }]); if (s.value[0]?.err) throw new Error("Transaction failed on Solana"); if (["confirmed", "finalized"].includes(s.value[0]?.confirmationStatus)) { setMessage(`${label} confirmed: ${signature}`); await load(); return; } await new Promise(r => setTimeout(r, 1000)); } throw new Error("Confirmation timed out; check explorer before retrying"); } catch (e) { setMessage(e instanceof Error ? e.message : "Transaction failed"); } };
  if (!allowed) return <main className="mx-auto max-w-5xl space-y-4 px-5 py-10"><WalletButton /><p role="alert" className="rounded border p-4">Connect the GlobalConfig admin wallet to access review.</p></main>;
  const orgQueue = data.organizations.filter(o => !o.unavailable && (!o.verified || o.status !== "Active")); const campaignQueue = data.campaigns.filter(c => !c.unavailable && c.status !== "Draft");
  return <main className="mx-auto max-w-6xl space-y-6 px-5 py-10"><header className="flex justify-between"><div><h1 className="text-3xl font-semibold">Admin review</h1><p className="text-sm text-muted">Canonical lifecycle state and digest-verified metadata.</p></div><WalletButton /></header>{message && <p role="status" className="break-all rounded border p-3">{message}</p>}<button className="rounded border px-3 py-2" onClick={() => void load()}>Refresh</button>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Organization review</h2>{orgQueue.map(o => <article className="space-y-2 rounded border p-4" key={o.address}><p className="break-all">{o.address}</p><p>{o.status} · {o.verified ? "Verified" : "Unverified"}</p><p className="break-all text-sm">On-chain digest: {o.metadataDigest}</p><p className="text-sm">Metadata: {o.metadata.state}</p><a className="underline text-sm" target="_blank" href={getExplorerUrl(`/address/${o.address}`)}>Explorer</a><div className="flex gap-2"><button disabled={isSending} className="rounded border px-3 py-2" onClick={() => void transact(() => setVerifiedIx(o, address(walletAddress!), !o.verified), o.verified ? "Organization verification revoked" : "Organization verified")}>{o.verified ? "Unverify" : "Verify"}</button>{o.status !== "Closed" && <button disabled={isSending} className="rounded border px-3 py-2" onClick={() => void transact(() => setStatusIx(o, address(walletAddress!), o.status === "Active" ? "Suspended" : "Active"), o.status === "Active" ? "Organization suspended" : "Organization activated")}>{o.status === "Active" ? "Suspend" : "Activate"}</button>}</div></article>)}</section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Campaign review</h2>{campaignQueue.map(c => <article className="space-y-2 rounded border p-4" key={c.address}><p className="break-all">{c.address}</p><p>{c.status} · target {c.targetAmount.toString()} lamports</p><p className="break-all text-sm">On-chain digest: {c.metadataDigest}</p><p className="text-sm">Metadata: {c.metadata.state}</p><a className="underline text-sm" target="_blank" href={getExplorerUrl(`/address/${c.address}`)}>Explorer</a><div className="flex flex-wrap gap-2">{c.status === "PendingReview" && <button disabled={isSending} className="rounded border px-3 py-2" onClick={() => void transact(() => setCampaignStatusIx(c, address(walletAddress!), "Active"), "Campaign activated")}>Activate</button>}{["PendingReview", "Active", "Paused"].includes(c.status) && <button disabled={isSending} className="rounded border px-3 py-2" onClick={() => void transact(() => setCampaignStatusIx(c, address(walletAddress!), "Closed"), "Campaign closed")}>Close</button>}{c.status === "Active" && <button disabled={isSending} className="rounded border px-3 py-2" onClick={() => void transact(() => setCampaignStatusIx(c, address(walletAddress!), "Paused"), "Campaign paused")}>Pause</button>}{c.status === "Paused" && <button disabled={isSending} className="rounded border px-3 py-2" onClick={() => void transact(() => setCampaignStatusIx(c, address(walletAddress!), "Active"), "Campaign reactivated")}>Reactivate</button>}</div>{c.fraudFlag?.resolution === "open" && <div className="flex gap-2 border-t pt-2"><span>Open advisory FraudFlag ({c.fraudFlag.score}/100)</span><button disabled={isSending} className="rounded border px-3 py-1" onClick={() => void transact(() => resolveFraudFlagIx(address(c.fraudFlag.address), address(walletAddress!), "resolved"), "FraudFlag resolved")}>Resolve</button><button disabled={isSending} className="rounded border px-3 py-1" onClick={() => void transact(() => resolveFraudFlagIx(address(c.fraudFlag.address), address(walletAddress!), "dismissed"), "FraudFlag dismissed")}>Dismiss</button></div>}</article>)}</section>
    <section><h2 className="text-xl font-semibold">Requested disaster campaigns</h2>{data.disasters.map(d => <p className="rounded border p-3" key={d.id}>{d.title} · {d.disaster_type} · {d.location} — <a className="underline" href="/admin/disasters">Review request</a></p>)}</section>
  </main>;
}
